### ISSUE TITLE
Messed up _zenroom.so file in PyPi package 1.0.12

### ISSUE THREAD

**Issue by zzappie** [dyne/Zenroom#116]
Hello zenroom keepers!

I've been playing around with zenroom recently and stumbled upon an issue with with pypi package.

After trying to `from zenroom import zenroom` I got this traceback:

```
Traceback (most recent call last):
  File "/root/.local/lib/python3.6/site-packages/zenroom/zenroom_swig.py", line 26, in swig_import_helper
    pkg = __name__.rpartition('.')[0]
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'zenroom._zenroom'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/.local/lib/python3.6/site-packages/zenroom/zenroom.py", line 5, in <module>
    from .zenroom_swig import zenroom_exec_tobuf, zencode_exec_tobuf
  File "/root/.local/lib/python3.6/site-packages/zenroom/zenroom_swig.py", line 32, in <module>
    _zenroom = swig_import_helper()
  File "/root/.local/lib/python3.6/site-packages/zenroom/zenroom_swig.py", line 26, in swig_import_helper
    pkg = __name__.rpartition('.')[0]
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: libpython3.7m.so.1.0: cannot open shared object file: No such file or directory
```

Which is strange since I have python 3.6.9 on that machine.
It turns out that not all _zenroom.so files are properly linked.

I went ran this ldd script in package directory.
```
for file in $(find | grep  .*_zenroom.so); do
    echo $(dirname $file) '->' $(ldd $file | grep -oE "libpython.{0,12}")
done
```
and got this:
```
./libs/Linux/3_6_2 -> libpython3.6m.so.1.0 libpython3.6m.so.1.0
./libs/Linux/3_6_5 -> libpython3.6m.so.1.0 libpython3.6m.so.1.0
./libs/Linux/3_7_2 -> libpython3.7m.so.1.0
./libs/Linux/3_5_0 -> libpython3.5m.so.1.0
./libs/Linux/3_6_4 -> libpython3.6m.so.1.0 libpython3.6m.so.1.0
./libs/Linux/3_5_1 -> libpython3.5m.so.1.0
./libs/Linux/3_6_6 -> libpython3.6m.so.1.0 libpython3.6m.so.1.0
./libs/Linux/3_7_0 -> libpython3.7m.so.1.0
./libs/Linux/3_5_2 -> libpython3.5m.so.1.0
./libs/Linux/3_5_4 -> libpython3.5m.so.1.0
./libs/Linux/3_6_3 -> libpython3.6m.so.1.0 libpython3.6m.so.1.0
./libs/Linux/3_6_9 -> libpython3.7m.so.1.0
./libs/Linux/3_7_4 -> libpython3.7m.so.1.0
./libs/Linux/3_5_3 -> libpython3.5m.so.1.0
./libs/Linux/3_6_7 -> libpython3.6m.so.1.0 libpython3.6m.so.1.0
./libs/Linux/3_6_1 -> libpython3.6m.so.1.0 libpython3.6m.so.1.0
./libs/Linux/3_7_3 -> libpython3.7m.so.1.0
./libs/Linux/3_5_5 -> libpython3.5m.so.1.0
./libs/Linux/3_6_8 -> libpython3.6m.so.1.0 libpython3.6m.so.1.0
./libs/Linux/3_6_0 -> libpython3.6m.so.1.0 libpython3.6m.so.1.0
./libs/Linux/3_7_1 -> libpython3.7m.so.1.0
./libs/Linux/3_5_6 -> libpython3.5m.so.1.0
```
If you look at  `3_6_9` line you'll see the mismatch.

**Comment by puria** [comment]
Yeah, I have in some corner of my hdd a cpython branch that builds, more like the approach of libsass, that compiles at installation time from the setup.py. But never had time to fully test and release. 
At some point would be nice to have a libzenroom distributed on different distributions, but I know it's a huge effort and will not happen in the near future...
If you want to help with the setup.py build as you mentioned I'm more than happy to support ;p

**Comment by zzappie** [comment]
Cool.  I'll give it a try then!

**Comment by puria** [comment]
closing this in favour of #125 and #136
